### ISSUE TITLE
Doesnt Work

### ISSUE THREAD

**Issue by Legend-Recalls** [wlauyeung/Skribblio-Helper#4]
i have latest chrome and noo other extensions conflicting
my suggestions all always empty
![image](https://user-images.githubusercontent.com/69719681/232346308-bcd27511-a119-42c6-ad06-074a45454189.png)

**Comment by wlauyeung** [comment]
Are you able to visit https://www.wlay.me/static/json/skribblio/words_v1.0.0.json ? If so, please share what settings are you currently running with in the popup page as well as the output for your development tool's console. Thanks.

**Comment by Legend-Recalls** [comment]
looks like your suspicion was correct, i am not able to reach wlay.me
![image](https://user-images.githubusercontent.com/69719681/232423991-ef4ee004-9765-4563-9a7b-7c5afe67dead.png)

**Comment by wlauyeung** [comment]
> looks like your suspicion was correct, i am not able to reach wlay.me
> ![image](https://user-images.githubusercontent.com/69719681/232423991-ef4ee004-9765-4563-9a7b-7c5afe67dead.png)

Do you know why are you unable to reach my site? Perhaps your local network/country has banned access to it for some reason? Are you using a custom DNS server that blacklisted my domain for some reason? Any idea would help.

**Comment by Legend-Recalls** [comment]
looks like my local network isp has blocked the site for reasons unknown, i used vpn and the site loads all well

**Comment by wlauyeung** [comment]
I see. I will try to find a more reliable place to host the file as a backup for users like you. Thanks for letting me know :)
